# Use an official OpenJDK runtime as a parent image
FROM openjdk:18.0.2.1-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy project files
COPY pom.xml .
COPY src ./src

# Install Maven
RUN apt-get update && apt-get install -y maven

# Build the application
RUN mvn clean package -D skipTests

# Expose the port the app runs on
EXPOSE 5454

# Run the jar file
ENTRYPOINT ["java","-jar","/app/target/treading-plateform-0.0.1-SNAPSHOT.jar"]