version: '3.8'
services:
  java-app:
    build: 
      context: .
    container_name: "treading-plateform"
    networks:
      - treading-plateform_nw
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/treading?allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2002
    depends_on:
      - mysql_db
    ports:
      - 5454:5454
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5454 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    
  mysql_db:
    image: mysql
    container_name: mysql
    networks:
      - treading-plateform_nw
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: treading
    restart: always
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-uroot","-p2002"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ./mysql-data:/var/lib/mysql
networks:
  treading-plateform_nw:

